name: Ansible Code Execution
on: [push]
jobs:
  ansible_ci:
    name: Run Ansible Checks
    runs-on: ubuntu-latest
    container: avdteam/base:3.6
    steps:
      - uses: actions/checkout@master
      - name: 'Install collections'
        run: |
          pip install -r requirements.txt
          make install
      - name: 'Check ansible syntax'
        run: |
          ansible-playbook playbooks/dc1-fabric-deploy-cvp.yml --syntax-check
          ansible-playbook playbooks/dc1-fabric-reset-cvp.yml --syntax-check
          ansible-playbook playbooks/dc1-ztp-configuration.yml --syntax-check
      - name: 'Run a generate playbook to test AVD variables'
        run: |
          ansible-playbook playbooks/dc1-fabric-deploy-cvp.yml --tags generate
      - name: 'Build AVD & CVP content'
        run: |
          ansible-playbook playbooks/dc1-fabric-deploy-cvp.yml --tags build
