name: Ansible Code Execution
on: [push]
jobs:
  ansible_ci:
    name: Run Ansible Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Install Python dependencies'
        run: make install-requirements
      - name: 'Install collections'
        run: make install
      - name: 'Check ansible syntax'
        run: |
          ansible-playbook dc1-fabric-deploy-cvp.yml --syntax-check
          ansible-playbook dc1-fabric-reset-cvp.yml --syntax-check
          ansible-playbook dc1-ztp-configuration.yml --syntax-check
      - name: 'Run a generate playbook to test AVD variables'
        run: |
          ansible-playbook dc1-fabric-deploy-cvp.yml --tags generate
      - name: 'Build AVD & CVP content'
        run: |
          ansible-playbook dc1-fabric-deploy-cvp.yml --tags build
      - name: 'Save Python libs version'
        run: |
          pip freeze
          pip freeze > intended/pip-version.txt
      - name: 'Remove collections'
        run: make uninstall
      - uses: actions/upload-artifact@v1
        with:
          name: intended-files
          path: intended/
      - name: 'Build mkdocs content to site folder'
        run: |
            make webdoc
      - name: 'Deploy last version to gh-pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./site
