name: Code Quality
on: [push]
jobs:
  code_linting:
    name: Run Python Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install development requirements
        run: make setup-repository
      - name: Yaml Linting
        run: make linting
